services:
  pg-wizdaa:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_DATABASE:-database}
    ports:
      - 5432:5432
    networks:
      - wizdaa
    volumes:
      - wizdaa-postgres:/var/lib/postgresql/data

  app-wizdaa:
    build: .
    container_name: app-wizdaa
    networks:
      - wizdaa
    depends_on:
      - pg-wizdaa
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: ['start:dev']

networks:
  wizdaa:
    driver: bridge
volumes:
  wizdaa-postgres:
    driver: local
